apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector-aggregator
  name: vector-aggregator
  namespace: openshift-osd-logforward
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vector-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app: vector-aggregator
      creationTimestamp: null
      labels:
        app: vector-aggregator
      name: vector-aggregator
      namespace: openshift-osd-logforward
    spec:
      containers:
      - env:
        image: quay.io/dciancio/vector
        imagePullPolicy: IfNotPresent
        name: vector
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 736Mi
          requests:
            cpu: 100m
            memory: 736Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/vector/vector.toml
          name: vector-aggregator-conf
          readOnly: true
          subPath: vector.toml
        - mountPath: /var/lib/vector
          name: filebufferstorage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 272
          name: vector-aggregator-conf
        name: vector-aggregator-conf
      - emptyDir: {}
        name: filebufferstorage
