apiVersion: v1
kind: Service
metadata:
  labels:
    app: vector-aggregator
  name: vector-aggregator
  namespace: openshift-osd-logforward
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: vector-aggregator
  sessionAffinity: None
  type: ClusterIP
